language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.0

install:
    - composer install

script:
    - php vendor/bin/tester tests -p phpdbg --coverage ./coverage.xml --coverage-src ./src

after_script:
    # Report Code Coverage
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config .coveralls.yml