language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.1

env:
    - NETTE_CACHE="^2.3"
    - NETTE_CACHE="^3.0.0-beta"

install:
    - composer install --no-interaction --prefer-source
    - composer require nette/caching:${NETTE_CACHE} --no-interaction --prefer-source

install:
    - composer install

script:
    - php vendor/bin/phpstan analyze ./src -l 5
    - php vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - php vendor/bin/tester tests -p phpdbg --coverage ./coverage.xml --coverage-src ./src

after_script:
    # Report Code Coverage
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config .coveralls.yml